name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        runs-on: [ubuntu-24.04, macos-14]
    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
            python-version: '3.8'
      - name: Test Draft
        run: |
          cd  ${{ github.workspace }}
          python -m venv .venv
          . .venv/bin/activate
          python -m pip install --upgrade pip setuptools
          python -m pip install -e .
          python dbz/draft.py --no-mpp --deck-size 1000 -q -s 0
